.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH gnome-screensaver 1 "2007\-09\-27" "GNOME"
.SH NAME
gnome-screensaver \- screen saver and locker
.SH SYNOPSIS
.B gnome-screensaver
.RI [ OPTIONS... ]
.SH DESCRIPTION
GNOME Screensaver is the default screen saver and locker in a GNOME
desktop. It is designed with simplicity and security in mind.
.SH OPTIONS
.TP
.B \-\-no\-daemon
Don't become a daemon
.TP
.B \-\-debug
Enable debugging code
.P
This program also accepts the standard GTK options.
.SH AUTHORS
.B gnome-screensaver
is written by William Jon McCann <mccann@jhu.edu>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>.
.SH SEE ALSO
.BR "gtk-options" (7)

