.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH gnome-screensaver-preferences 1 "2007\-09\-27" "GNOME"
.SH NAME
gnome-screensaver-preferences \- configure GNOME Screensaver
.SH SYNOPSIS
.B gnome-screensaver-preferences
.RI [ OPTIONS... ]
.SH DESCRIPTION
Manages preferences for the GNOME screen saver.
.SH OPTIONS
This program only accepts the standard GTK options.
.SH AUTHORS
.B gnome-screensaver-preferences
is written by William Jon McCann <mccann@jhu.edu>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>.
.SH SEE ALSO
.BR "gnome-screensaver" (1),
.BR "gtk-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
