.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\" Copyright (C) 2014 Peter de Ridder <peter@xfce.org>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH LIGHT-LOCKER-COMMAND 1 "2014\-03\-23" "The Cavalry"
.SH NAME
light-locker-command \- controls light-locker
.SH SYNOPSIS
.B light-locker-command
.RI [ OPTION... ]
.SH DESCRIPTION
light-locker-command is a tool for controlling an already
running instance of light-locker.
This is done through LightDM which doesn't ensure light-locker is running.
.SH OPTIONS
.TP
.B \-q, \-\-query
Query the state of the locker
.TP
.B \-t, \-\-time
Query the length of time the locker has been active
.TP
.B \-l, \-\-lock
Tells the running locker process to lock the screen immediately
.TP
.B \-a, \-\-activate
Turn the screensaver on (blank the screen)
.TP
.B \-d, \-\-deactivate
If the screensaver is active then deactivate it (un-blank the screen)
.TP
.B \-p, \-\-poke
Poke the running locker to simulate user activity
.TP
.B \-i, \-\-inhibit
Inhibit the screensaver from activating. Terminate the light-locker-command process to end inhibition.
.TP
.B \-n, \-\-application-name
The calling application that is inhibiting the screensaver
.TP
.B \-r, \-\-reason
The reason for inhibiting the screensaver
.TP
.B \-V, \-\-version
Version of this application
.SH SEE ALSO
.BR "light-locker" (1)

