.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\" Copyright (C) 2014 Peter de Ridder <peter@xfce.org>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH LIGHT\-LOCKER 1 "2014\-03\-23" "The Cavalry"
.SH NAME
light\-locker \- screen locker
.SH SYNOPSIS
.B light\-locker
.RI [ OPTIONS... ]
.SH DESCRIPTION
light\-locker is a simple locker (forked from gnome\-screensaver)
that aims to have a simple, sane, secure defaults and be well
integrated with the desktop while not carrying any desktop\-specific
dependencies.
.SH OPTIONS
.TP
.B \-\-debug
Enable debugging code
.TP
.BI \-\-lock\-after\-screensaver\fR=\fIS
Lock the screen S seconds after the screensaver started.
Use 0 to disable this
.TP
.B \-\-late\-locking
Lock the screen on screensaver deactivation
.TP
.B \-\-no\-late\-locking
Lock the screen on screensaver activation
.TP
.B \-\-lock\-on\-suspend
Lock the screen on suspend/resume
.TP
.B \-\-no\-lock\-on\-suspend
Do not lock the screen on suspend/resume
.TP
.B \-\-lock\-on\-lid
Lock the screen on lid close
.TP
.B \-\-no\-lock\-on\-lid
Do not lock the screen on lid close
.TP
.B \-\-idle\-hint
Set the session idle hint while the screenaver is active
.TP
.B \-\-no\-idle\-hint
Don't set the idle hint. Let something else handle that
.P
This program also accepts the standard GTK options.
.SH SEE ALSO
.BR "gtk-options" (7)

